apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app
    image: nginx
    volumeMounts:
    - name: app-bundle
      mountPath: /etc/app
  volumes:
  - name: app-bundle
    projected:
      sources:
      - configMap:
          name: app-config
          items:
          - key: app.yaml
            path: app.yaml
      - secret:
          name: app-secret
          items:
          - key: db_password
            path: db_password
      - downwardAPI:
          items:
          - path: namespace
            fieldRef:
              fieldPath: metadata.namespace
