apiVersion: v1
kind: Pod
metadata:
  labels:
    run: dyn-user-1
  name: dyn-user-1
  namespace: cka-storage-4
spec:
  volumes:
  - name: dyn-pvc 
    persistentVolumeClaim:
      claimName: pvc-dynamic-1
  containers:
  - image: nginx
    name: dyn-user-1
    command: ['sh','-c','echo "WRITE"; echo "from dyn-user-1 into /data/hello" | tee /data/hello.txt; sleep 3600']
    volumeMounts:
    - name: dyn-pvc
      mountPath: /data    
