apiVersion: v1
kind: Pod
metadata:
  labels:
    run: hostpath-writer
  name: hostpath-writer
  namespace: cka-storage-2
spec:
  nodeName: k3d-lab-agent-0
  volumes:
  - name: host
    hostPath: 
      path: /data/test
      type: DirectoryOrCreate
  containers:
  - image: nginx
    name: hostpath-writer
    command: ['sh','-c','echo "this is hostpath cka" > /hostdata/node-file.txt; sleep 3600']
    volumeMounts:
    - name: host
      mountPath: /hostdata
