apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-static-1
spec:
  hostPath:
    path: /data
    type: DirectoryOrCreate
  accessModes: 
  - ReadWriteOnce
  capacity: 
    storage: '1Gi'
  persistentVolumeReclaimPolicy: Retain
