apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-fast-dyn
  namespace: cka-storage-7
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: '150Mi'
  storageClassName: local-path
