apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-too-big-1
  namespace: cka-storage-6
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: '5Gi'
  storageClassName: ""
