apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-fast-1
  namespace: cka-storage-7
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: '200Mi'
  storageClassName: ""
