apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-dynamic-1
  namespace: cka-storage-4
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: '200Mi'
  storageClassName: local-path
