apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-static-1
  namespace: cka-storage-3
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: '500Mi'
  storageClassName: ""
