apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rwo-1
  namespace: cka-storage-5
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: '100Mi'
  storageClassName: local-path
