apiVersion: v1
kind: Pod
metadata:
  labels:
    run: row-a
  name: row-a
  namespace: cka-storage-5
spec:
  volumes:
  - name: dyn-pvc 
    persistentVolumeClaim:
      claimName: pvc-rwo-1
  containers:
  - image: nginx
    name: row-a
    command: ['sh','-c','echo "WRITE"; echo "from row-a into /data/hello" | tee /data/hello.txt; sleep 3600']
    volumeMounts:
    - name: dyn-pvc
      mountPath: /data    
