apiVersion: v1
kind: Pod
metadata:
  labels:
    run: no-tol
  name: no-tol
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disk
            operator: In
            values:
            - ssd        
  containers:
  - image: nginx
    name: no-tol
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
