apiVersion: v1
kind: Pod
metadata:
  labels:
    run: rl-pod
  name: rl-pod
spec:
  containers:
  - image: nginx
    name: rl-pod
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
