apiVersion: v1
kind: Pod
metadata:
  labels:
    run: rq-pod
  name: rq-pod
spec:
  containers:
  - image: nginx
    name: rl-pod
    resources:
      requests:
        memory: "500Mi"
        cpu: "500m"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
