apiVersion: v1
kind: Pod
metadata:
  labels:
    run: web-app
  name: web-app
spec:
  containers:
  - image: nginx:alpine
    name: web-app
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
