apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: broken-pvc
  namespace: storage-test
spec:
  storageClassName: "manual"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
