apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fast-pvc
  namespace: sc-test
spec:
  storageClassName: fast-sc
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
